keys:
  - &default age1nagxclkx6uyj2f8yhah0uztearcy9syjf2dyawwg8k6e9nxl63psdlp78s
  - &scuffed age1ffkf8al0q72kh5yzhgg46zlaa2ptn8kkxaz8dc2dvuf3assetqgqmjnqvj
  - &chuwi age1hrnulhnz9qpyhpeplkcrauk26kwlk8x27mlfuu2ja2qsucqal5aswj0vny
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *default
      - *scuffed
      - *chuwi
